//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDRAEntities : DbContext
    {
        public BDRAEntities()
            : base("name=BDRAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<additionalInformationByContact> additionalInformationByContact { get; set; }
        public virtual DbSet<ally> ally { get; set; }
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<CashSpecialist> CashSpecialist { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CNE> CNE { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EconomicActivity> EconomicActivity { get; set; }
        public virtual DbSet<jobTitle> jobTitle { get; set; }
        public virtual DbSet<JobTitlesClient> JobTitlesClient { get; set; }
        public virtual DbSet<kindOfAlly> kindOfAlly { get; set; }
        public virtual DbSet<KindOfBanking> KindOfBanking { get; set; }
        public virtual DbSet<kindOfDocument> kindOfDocument { get; set; }
        public virtual DbSet<logins> logins { get; set; }
        public virtual DbSet<modules> modules { get; set; }
        public virtual DbSet<operationalInformationByRequest> operationalInformationByRequest { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<permissionByModule> permissionByModule { get; set; }
        public virtual DbSet<permissionByRole> permissionByRole { get; set; }
        public virtual DbSet<probability> probability { get; set; }
        public virtual DbSet<Regional> Regional { get; set; }
        public virtual DbSet<RegionalsMain> RegionalsMain { get; set; }
        public virtual DbSet<RegionalsVice> RegionalsVice { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<riskInformationByRequest> riskInformationByRequest { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<Segment> Segment { get; set; }
        public virtual DbSet<stateGroup> stateGroup { get; set; }
        public virtual DbSet<states> states { get; set; }
        public virtual DbSet<userByRol> userByRol { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<VicePresident> VicePresident { get; set; }
        public virtual DbSet<Zonal> Zonal { get; set; }
        public virtual DbSet<VP> VP { get; set; }
    
        public virtual ObjectResult<RA_SP_GetDataToFile_Result> RA_SP_GetDataToFile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RA_SP_GetDataToFile_Result>("RA_SP_GetDataToFile");
        }
    }
}
